sim_setup_params:
  rand_seed: 99
protocol_params:
  delays:
    config_update_delay: "172800" # 2 days
    config_update_grace_period: "259200" # 3 days
    min_deposit_duration: "86400" # 1 day
    redemption_delay: "43200" # 1/2 days
    purchase_delay: "57600" # 2/3 days
  fees:
    deposit_fee_reserves: 0
    deposit_fee_backstop: 0
    purchase_fee_reserves: 0
    purchase_fee_backstop: 0
    sale_fee_reserves: 0
    sale_fee_backstop: 0
  allowed_markets_per_set: "50"
base_token_params:
  name: "Cozy Base Token"
  symbol: "CBT"
  decimals: 6
