name: Checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: cargo test
        run: cargo test --all --all-features --exclude bindings

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          components: rustfmt, clippy
          override: true

      - uses: Swatinem/rust-cache@v1
        with:
          cache-on-failure: true

      - name: cargo fmt
        run: cargo +nightly fmt -p binder -- --check

      - name: cargo fmt
        run: cargo +nightly fmt -p simulate -- --check

      - name: cargo fmt
        run: cargo +nightly fmt -p simulations -- --check

      - name: cargo clippy
        run: cargo +nightly clippy -p binder --all-features -- -D warnings

      - name: cargo clippy
        run: cargo +nightly clippy -p simulate --all-features -- -D warnings

      - name: cargo clippy
        run: cargo +nightly clippy -p simulations --no-deps --all-features -- -D warnings
